### ISSUE TITLE
set path-to-file to assets (on Android) and bundle dir (on iOS)

### ISSUE THREAD

**Issue by sebqq** [ez-connect/react-native-binary-file#1]
Hello! 

I'm trying to use react-native-binary-file and I'm not able to open my file located in assets (android) and bundle dir (ios). I would like to ask you how to format a path arg.

Currently, I'm using a constant from react-native-fs in order do get path to main bundle for iOS`RNFS.MainBundlePath` and code looks like:

```javascript
...
import RNFS from "react-native-fs";
import { BinaryFile } from "react-native-binary-file";

...

const binaryPathPrefix = Platform.OS === "ios" ? RNFS.MainBundlePath + "/" : "";

const readHeightMap = async hole => {
  const path = `${binaryPathPrefix}binary_file.hgh`;
  const fd = await BinaryFile.open(path);
  return fd;
};
```

output from Chrome debug console

```
YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'open' of undefined
TypeError: Cannot read property 'open' of undefined
    at BinaryFile.open (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:154823:23)
    at readHeightMap$ (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:144983:118)
    at tryCatch (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:37888:19)
    at Generator.invoke [as _invoke] (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:38063:24)
    at Generator.prototype.<computed> [as next] (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:37931:23)
    at tryCatch (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:37888:19)
    at invoke (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:37964:22)
    at blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:37994:13
    at tryCallTwo (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:9429:7)
    at doResolve (blob:http://localhost:8081/ba9dc707-066d-46d5-bbd8-258b7997c32d:9593:15)
```

Output when JS debbuging is off:
![Simulator Screen Shot - iPhone X - 2019-09-28 at 14 26 19](https://user-images.githubusercontent.com/33039909/65816446-f978df80-e1fb-11e9-8fdd-9aabe8034065.png)

I've installed app using 

```bash
yarn add react-native-binary-file
cd ios
pod install
```

Thank you so much for any help!

```
react-native: 0.60.5
```

**Comment by sebqq** [comment]
I've found that RNBinaryFile was not find in NativeModules but I don't know why. I'll keep digging. I even tried to use `react-native link react-native-binary-file` and clean build folder and build once again.

**Comment by sebqq** [comment]
@thanh-vinh I've upgraded react-native to 0.61.1 and added use_frameworks! to podfile but I'm still unable to use react-native-binary-file :( any help? Thanks!

**Comment by vnhdx** [comment]
I’m looking into the issue. Thanks for your report!

**Update**

It won't allow to open a file in bundle / assets directly. Copy that file to a readable path, `RNFS.DocumentDirectoryPath` for example, then open it.

**Comment by sofianegargouri** [comment]
I have the same problem using `RNFS.DocumentDirectoryPath`

For me it's not even a problem about the path, but it's about the linking of the module I guess. NativeModules is empty for me, that's why we have the error. 

I'm running React Native 0.60+, I ran `yarn add react-native-binary-file` and `pod install` in the `ios` folder

**Comment by ishtiaq-punch** [comment]
Please change this line in podspec file 

s.source_files  = "RNBinaryFile/**/*.{h,m,swift}"

to 

s.source_files  = "ios**/*.{h,m,swift}"
